INSERT INTO pricing_settings (id, key, value, description, updated_at) VALUES
(gen_random_uuid(), 'DAILY_FREE_CREDITS', '{"amount": 5, "description": "Daily free credits allocated to each active user"}'::jsonb, 'Daily free credits amount', NOW()),
(gen_random_uuid(), 'ANNUAL_DISCOUNT_PERCENTAGE', '{"percentage": 20, "description": "Discount applied to annual package purchases"}'::jsonb, 'Annual billing discount percentage', NOW()),
(gen_random_uuid(), 'DEFAULT_CURRENCY', '{"currency": "INR", "symbol": "₹"}'::jsonb, 'Default platform billing currency', NOW())
ON CONFLICT (key) DO NOTHING;

INSERT INTO credit_packages (id, slug, name, description, price_inr, credits, user_limit, billing_type, popular, features, badge_text, is_active, sort_order, created_at, updated_at) VALUES
('5b11b41d-4451-4ea3-9ace-be33b7a18ad4', 'free', 'Free Plan', 'Standard access for early prospecting and exploring verified business intelligence.', 0, 5, 1, 'DAILY_FREE', false, '["5 Daily Verified Leads", "Search and Discovery Engine", "Basic Contact Details", "Daily rollover at 11:59 PM", "Community Support"]'::jsonb, '5 Daily Free', true, 1, NOW(), NOW()),
('30ad3ee3-f861-4a59-b374-5af11f820194', 'starter', 'Starter Pack', 'Ideal for individual founders, freelancers, and sales reps building focused pipelines.', 99, 100, 1, 'ONE_TIME', false, '["100 Lifetime Lead Credits", "Credits Never Expire", "Direct Mobile and Email Unlocks", "CSV / Spreadsheet Export", "Single User License", "Standard Support"]'::jsonb, null, true, 2, NOW(), NOW()),
('cdcc091d-282c-4bd6-93d2-2f5aa1955110', 'growth', 'Growth Pack', 'Best for growing sales teams and agencies looking for rapid pipeline scale.', 299, 350, 1, 'ONE_TIME', true, '["350 Lifetime Lead Credits", "Credits Never Expire", "Direct Decision Maker Contacts", "Full Export and Filter Capabilities", "Single User License", "Priority Email Support"]'::jsonb, 'Most Popular', true, 3, NOW(), NOW()),
('b8dfcad5-f348-40b7-801d-38124b909425', 'agency', 'Agency Pack', 'High-volume lead intelligence for outreach agencies and enterprise outbound teams.', 999, 1500, 1, 'ONE_TIME', false, '["1,500 Lifetime Lead Credits", "Credits Never Expire", "Full Executive and CXO Contacts", "Bulk Export Engine", "Single User License", "Priority VIP Support"]'::jsonb, 'Best Value', true, 4, NOW(), NOW()),
('c31b8ca8-a484-46cb-b30d-675acfaefdb8', 'enterprise', 'Enterprise Plan', 'Custom high-volume intelligence, dedicated infrastructure, and team workspace management.', null, 0, null, 'CUSTOM', false, '["Custom High-Volume Credit Allocation", "Unlimited Team Users and RBAC", "Team Workspace Collaboration", "Bulk Export Engine", "Dedicated API Access", "24x7 Priority Account Manager"]'::jsonb, 'Custom', true, 5, NOW(), NOW())
ON CONFLICT (slug) DO NOTHING;
